### ISSUE TITLE
关于数据库一些数据

### ISSUE THREAD

**Issue by MoonCheung** [xxxsimons/mpvue-cloud#4]
您好，自从下载您的mpvue-cloud源代码打开查看没有相关数据库数据信息的，不过请问您那边是否有这个数据库数据信息提供给我练手下，谢谢呢

**Comment by MoonCheung** [comment]
没人回复吗？

**Comment by Rychou** [comment]
不好意思 前段时间没看到邮件 你要看数据库的话应该是需要添加你为管理员的

**Comment by MoonCheung** [comment]
怎么添加我作为管理员呢？

**Comment by Rychou** [comment]
@MoonCheung 添加管理员不太方便 添加了你就能登录这个小程序后台了  数据库没什么数据 你看着文档也是一样的
